version: '3.8'

services:
  api:
    build: .
    container_name: hops-meta-api
    platform: linux/amd64
    restart: always
    environment:
      - FLASK_ENV=production
      - HTTP_PROXY=${HTTP_PROXY:-}
      - HTTPS_PROXY=${HTTPS_PROXY:-}
    ports:
      - "5052:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
